# THESE ARE JUST DUMMY VALUES, CREATE YOUR OWN SETTINGS IN 'my_settings.py' IN THIS FORMAT:
BOARD_IDS = ["dummyBoardID1", "dummyBoardID2"]
DEFAULT_TARGET_LIST_ID = "dummyTargetListID"
MEMBER_NAME_ID_PAIRS = {"Name1": "IDName1", "Name2": "IDName2"}
NUMBER_OF_DAYS_TO_CONSIDER_IN_THE_SEARCH = 5

